### ISSUE TITLE
Missing domain

### ISSUE THREAD

**Issue by jgbishop** [jkrejcha/AdmiraList#2]
My [local news website](https://www.wral.com/) uses Admiral (they just started), and are serving their instance from `unequalbrake.com`. I didn't see this one in your list, and figured I'd report it.

**Comment by paulej** [comment]
Yep, I ran into the same one  It should definitely be on the list.

**Comment by TNW9imKLC3fv** [comment]
More discussion of this here: https://github.com/paulgb/BarbBlock/issues/4 - it might be worth @jkrejcha and others collaborating with the authors of this addon, from what people are saying it's going to be an ongoing issue keeping it updated - one suggestion people mentioned to jump to in that thread is "ASN blocking"

**Comment by jkrejcha** [comment]
Implemented in #3, but leaving this issue open so further discussion can happen on this, mostly in relation to @TNW9imKLC3fv's comment
